#!/bin/bash
# Sets up ZYNQ_TOOLBOX and VIVADO_PATH, sources settings64.sh, and
# (re)generates ~/.Xilinx/Vivado/Vivado_init.tcl on every container start.

set -e

TOOLS_ROOT="/tools/Xilinx/Vivado"
REPO_ROOT="/workspace/zynq_toolbox"

if [ -d "$REPO_ROOT" ]; then
    export ZYNQ_TOOLBOX="$REPO_ROOT"
else
    echo "WARNING: $REPO_ROOT not found." >&2
    echo "         Mount your zynq_toolbox checkout there, e.g.:" >&2
    echo "         -v \$(pwd):/workspace/zynq_toolbox" >&2
fi

# Auto-detect the installed version from the vivado-tools volume, unless
# pinned via `docker run -e VIVADO_VERSION=2024.2 ...`
if [ -z "$VIVADO_VERSION" ] && [ -d "$TOOLS_ROOT" ]; then
    VIVADO_VERSION="$(ls "$TOOLS_ROOT" 2>/dev/null | sort -V | tail -n1)"
fi

if [ -n "$VIVADO_VERSION" ]; then
    export VIVADO_VERSION
    export VIVADO_PATH="$TOOLS_ROOT/$VIVADO_VERSION"
else
    echo "WARNING: no Vivado install found under $TOOLS_ROOT." >&2
    echo "         Mount your vivado-tools volume at /tools/Xilinx, e.g.:" >&2
    echo "         -v vivado-tools:/tools/Xilinx" >&2
fi

if [ -f "$VIVADO_PATH/settings64.sh" ]; then
    source "$VIVADO_PATH/settings64.sh"
else
    echo "WARNING: Vivado settings64.sh not found at $VIVADO_PATH" >&2
fi

if [ -n "$ZYNQ_TOOLBOX" ]; then
    mkdir -p "$HOME/.Xilinx/Vivado"
    cat > "$HOME/.Xilinx/Vivado/Vivado_init.tcl" <<EOF
# Auto-generated by entrypoint-vivado.sh -- do not edit by hand
set zynq_toolbox \$::env(ZYNQ_TOOLBOX)
source \$zynq_toolbox/scripts/vivado/repo_paths.tcl
EOF
fi

exec "$@"