#!/bin/bash
# Dispatches based on $ZYNQ_MODE (set by docker-compose.yml per-service, or
# pass `-e ZYNQ_MODE=...` on a bare `docker run`):
#
#   tools    -> hand off to setup-tools.sh   (installer / cocotb / verilator)
#   offline  -> hand off to setup-offline.sh (sstate-cache / downloads)
#   dev      -> (default) set up env vars for the actual build environment,
#               same job entrypoint.sh always did, then exec the CMD/command.

set -e

MODE="${ZYNQ_MODE:-dev}"

case "$MODE" in
  tools)
    exec /usr/local/bin/setup_tools.sh "$@"
    ;;
  offline)
    exec /usr/local/bin/setup_offline.sh "$@"
    ;;
  dev)
    TOOLS_ROOT="/tools/Xilinx"
    OFFLINE_ROOT="/tools/petalinux_offline"
    REPO_ROOT="/workspace/zynq_toolbox"

    # ---- ZYNQ_TOOLBOX ---------------------------------------------------
    if [ -d "$REPO_ROOT" ]; then
        export ZYNQ_TOOLBOX="$REPO_ROOT"
    else
        echo "WARNING: $REPO_ROOT not found." >&2
        echo "         Mount your zynq_toolbox checkout there, e.g.:" >&2
        echo "         -v \$(pwd):/workspace/zynq_toolbox" >&2
    fi

    # ---- PETALINUX_VERSION / PETALINUX_PATH / VIVADO_PATH ---------------
    # Auto-detect the installed version from the tools volume, unless
    # pinned via `-e PETALINUX_VERSION=2024.2` (needed if more than one
    # version is installed side by side).
    if [ -z "$PETALINUX_VERSION" ] && [ -d "$TOOLS_ROOT/PetaLinux" ]; then
        PETALINUX_VERSION="$(ls "$TOOLS_ROOT/PetaLinux" 2>/dev/null | sort -V | tail -n1)"
    fi

    if [ -n "$PETALINUX_VERSION" ]; then
        export PETALINUX_VERSION
        export PETALINUX_PATH="$TOOLS_ROOT/PetaLinux/$PETALINUX_VERSION/tool"
        export VIVADO_PATH="$TOOLS_ROOT/Vivado/$PETALINUX_VERSION"
    else
        echo "WARNING: no PetaLinux install found under $TOOLS_ROOT/PetaLinux." >&2
        echo "         Mount your tools volume there, e.g.:" >&2
        echo "         -v zynq-tools:/tools/Xilinx" >&2
    fi

    # ---- Source Vivado's environment script ------------------------------
    if [ -f "$VIVADO_PATH/settings64.sh" ]; then
        source "$VIVADO_PATH/settings64.sh"
    else
        echo "WARNING: Vivado settings64.sh not found at $VIVADO_PATH" >&2
    fi

    # ---- Generate ~/.Xilinx/Vivado/Vivado_init.tcl -----------------------
    if [ -n "$ZYNQ_TOOLBOX" ]; then
        mkdir -p "$HOME/.Xilinx/Vivado"
        cat > "$HOME/.Xilinx/Vivado/Vivado_init.tcl" <<EOF
# Auto-generated by entrypoint.sh -- do not edit by hand
set zynq_toolbox \$::env(ZYNQ_TOOLBOX)
source \$zynq_toolbox/scripts/vivado/repo_paths.tcl
EOF
    fi

    # ---- cocotb, if installed into the tools volume ----------------------
    if [ -d "$TOOLS_ROOT/cocotb" ]; then
        export PYTHONUSERBASE="$TOOLS_ROOT/cocotb"
        export PATH="$TOOLS_ROOT/cocotb/bin:$PATH"
    fi

    # ---- Verilator, if built into the tools volume ------------------------
    if [ -d "$TOOLS_ROOT/verilator/bin" ]; then
        export PATH="$TOOLS_ROOT/verilator/bin:$PATH"
    fi

    # ---- PetaLinux offline cache, auto-detected from the offline volume --
    # Can still be overridden with -e PETALINUX_DOWNLOADS_PATH=... / -e
    # PETALINUX_SSTATE_PATH=... if you keep the cache somewhere else.
    if [ -z "$PETALINUX_DOWNLOADS_PATH" ] && [ -d "$OFFLINE_ROOT/downloads" ]; then
        export PETALINUX_DOWNLOADS_PATH="$OFFLINE_ROOT/downloads"
    fi
    if [ -z "$PETALINUX_SSTATE_PATH" ] && [ -d "$OFFLINE_ROOT/arm" ]; then
        export PETALINUX_SSTATE_PATH="$OFFLINE_ROOT/arm"
    fi

    exec "$@"
    ;;
  *)
    echo "ERROR: unknown ZYNQ_MODE '$MODE' (expected tools, offline, or dev)" >&2
    exit 1
    ;;
esac