#!/bin/bash
# Replaces the "Profile setup" and "Vivado init script" steps from a bare-VM
# install. Because the container's mount points are fixed by convention
# (see docker/README.md), we derive the same variables environment.sh would
# have held, and (re)generate Vivado_init.tcl on every container start
# instead of requiring a one-time manual edit.

set -e

TOOLS_ROOT="/tools/Xilinx"
REPO_ROOT="/workspace/zynq_toolbox"

# ---- ZYNQ_TOOLBOX ----------------------------------------------------------
if [ -d "$REPO_ROOT" ]; then
    export ZYNQ_TOOLBOX="$REPO_ROOT"
else
    echo "WARNING: $REPO_ROOT not found." >&2
    echo "         Mount your zynq_toolbox checkout there, e.g.:" >&2
    echo "         -v \$(pwd)/zynq_toolbox:/workspace/zynq_toolbox" >&2
fi

# ---- PETALINUX_VERSION / PETALINUX_PATH / VIVADO_PATH ---------------------
# Auto-detect the installed version from the tools volume, unless pinned
# via `docker run -e PETALINUX_VERSION=2024.2 ...` (needed if more than one
# version is installed side by side).
if [ -z "$PETALINUX_VERSION" ] && [ -d "$TOOLS_ROOT/PetaLinux" ]; then
    PETALINUX_VERSION="$(ls "$TOOLS_ROOT/PetaLinux" 2>/dev/null | sort -V | tail -n1)"
fi

if [ -n "$PETALINUX_VERSION" ]; then
    export PETALINUX_VERSION
    export PETALINUX_PATH="$TOOLS_ROOT/PetaLinux/$PETALINUX_VERSION/tool"
    export VIVADO_PATH="$TOOLS_ROOT/Vivado/$PETALINUX_VERSION"
else
    echo "WARNING: no PetaLinux install found under $TOOLS_ROOT/PetaLinux." >&2
    echo "         Mount your tools volume there, e.g.:" >&2
    echo "         -v xilinx-tools:/tools/Xilinx" >&2
fi

# ---- Source Vivado's environment script ------------------------------------
if [ -f "$VIVADO_PATH/settings64.sh" ]; then
    source "$VIVADO_PATH/settings64.sh"
else
    echo "WARNING: Vivado settings64.sh not found at $VIVADO_PATH" >&2
fi

# ---- Generate ~/.Xilinx/Vivado/Vivado_init.tcl -----------------------------
if [ -n "$ZYNQ_TOOLBOX" ]; then
    mkdir -p "$HOME/.Xilinx/Vivado"
    cat > "$HOME/.Xilinx/Vivado/Vivado_init.tcl" <<EOF
# Auto-generated by entrypoint.sh -- do not edit by hand
set zynq_toolbox \$::env(ZYNQ_TOOLBOX)
source \$zynq_toolbox/scripts/vivado/repo_paths.tcl
EOF
fi

# ---- Optional: PetaLinux offline build cache -------------------------------
# If using offline PetaLinux builds, mount the extracted cache directories
# and pass their paths at `docker run` time, e.g.:
#   -v /host/path/to/downloads:/workspace/petalinux_downloads:ro \
#   -v /host/path/to/sstate/arm:/workspace/petalinux_sstate:ro \
#   -e PETALINUX_DOWNLOADS_PATH=/workspace/petalinux_downloads \
#   -e PETALINUX_SSTATE_PATH=/workspace/petalinux_sstate
# They just pass through as env vars; nothing to do here.

exec "$@"